# Generated by Django 2.2.2 on 2019-07-02 15:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Menu title')),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(regex='^[-a-zA-Z0-9_]+$')], verbose_name='Menu system name (^[-a-zA-Z0-9_]+$)')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('title_cached', models.CharField(blank=True, max_length=128, null=True, verbose_name='Title cached')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='URL slug')),
                ('slug_cached', models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='URL cached slug')),
                ('url_named', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Named url')),
                ('url', models.URLField(blank=True, max_length=2048, null=True, verbose_name='Pure url')),
                ('url_cached', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Url cahed')),
                ('level_cached', models.PositiveSmallIntegerField(default=0, verbose_name='Branch level')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Branch')),
            ],
        ),
    ]
